(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(abbrev-suggest t)
 '(ace-window-display-mode t)
 '(after-save-hook '(executable-make-buffer-file-executable-if-script-p))
 '(apropos-compact-layout t)
 '(auto-hscroll-mode 'current-line)
 '(aw-dispatch-always nil)
 '(aw-dispatch-when-more-than 1)
 '(aw-keys '(49 50 51 52 53 54 55 56 57))
 '(beacon-blink-delay 0.7)
 '(beacon-blink-duration 1)
 '(beacon-blink-when-point-moves-horizontally 1)
 '(beacon-blink-when-point-moves-vertically 1)
 '(beacon-color "sienna1")
 '(beacon-dont-blink-commands nil)
 '(blink-cursor-delay 0.2)
 '(blink-cursor-interval 0.2)
 '(blink-cursor-mode nil)
 '(bmkp-last-as-first-bookmark-file "~/.emacs.d/bookmarks")
 '(bookmark-use-annotations t)
 '(calendar-and-diary-frame-parameters
   '((name . "Calendar")
     (title . "Calendar")
     (height . 60)
     (width . 80)
     (minibuffer)))
 '(calendar-mark-diary-entries-flag t)
 '(calendar-view-diary-initially-flag t)
 '(company-async-redisplay-delay 1)
 '(company-idle-delay 2)
 '(company-keywords-ignore-case t)
 '(company-tooltip-idle-delay 1.5)
 '(confirm-kill-emacs 'y-or-n-p)
 '(counsel-describe-function-function 'helpful-callable)
 '(counsel-describe-variable-function 'helpful-variable)
 '(counsel-mode t)
 '(counsel-mode-override-describe-bindings t)
 '(cursor-in-non-selected-windows 'hollow)
 '(cursor-type 'box)
 '(custom-browse-only-groups nil)
 '(custom-browse-order-groups 'last)
 '(custom-browse-sort-alphabetically t)
 '(custom-buffer-done-kill t)
 '(custom-buffer-order-groups 'first)
 '(custom-buffer-sort-alphabetically t)
 '(custom-enabled-themes '(cyberpunk))
 '(custom-magic-show-button nil)
 '(custom-safe-themes
   '("a1c18db2838b593fba371cb2623abd8f7644a7811ac53c6530eebdf8b9a25a8d" default))
 '(custom-unlispify-remove-prefixes t)
 '(cycle-spacing-actions
   '(just-one-space delete-all-space restore delete-space-after delete-space-before))
 '(dashboard-navigator-buttons nil)
 '(dashboard-page-separator "\12\12")
 '(dashboard-projects-backend 'project-el)
 '(dashboard-vertically-center-content t)
 '(debug-on-error t)
 '(default-input-method "rfc1345")
 '(delete-selection-mode t)
 '(diary-file "~/iCloud/org/diary")
 '(dimmer-fraction 0.7)
 '(dired-auto-revert-buffer 'dired-directory-changed-p)
 '(display-buffer-alist nil)
 '(duplicate-line-final-position 1)
 '(dynamic-completion-mode t)
 '(ediff-split-window-function 'split-window-horizontally)
 '(etags-xref-prefer-current-file t)
 '(ffap-file-name-with-spaces t)
 '(focus-follows-mouse t)
 '(global-prettify-symbols-mode t)
 '(global-so-long-mode t)
 '(grep-find-command
   '("find -L . -type f -exec grep --color=auto -nH --null -e  \\{\\} +" . 54))
 '(grep-find-ignored-files
   '(".#*" "*.o" "*~" "*.bin" "*.lbin" "*.so" "*.a" "*.ln" "*.blg" "*.bbl" "*.elc" "*.lof" "*.glo" "*.idx" "*.lot" "*.fmt" "*.tfm" "*.class" "*.fas" "*.lib" "*.mem" "*.x86f" "*.sparcf" "*.dfsl" "*.pfsl" "*.d64fsl" "*.p64fsl" "*.lx64fsl" "*.lx32fsl" "*.dx64fsl" "*.dx32fsl" "*.fx64fsl" "*.fx32fsl" "*.sx64fsl" "*.sx32fsl" "*.wx64fsl" "*.wx32fsl" "*.fasl" "*.ufsl" "*.fsl" "*.dxl" "*.lo" "*.la" "*.gmo" "*.mo" "*.toc" "*.aux" "*.cp" "*.fn" "*.ky" "*.pg" "*.tp" "*.vr" "*.cps" "*.fns" "*.kys" "*.pgs" "*.tps" "*.vrs" "*.pyc" "*.pyo" "TAGS" "tags"))
 '(grep-find-template
   "find -H -L <D> <X> -type f <F> -exec grep <C> -nH --null -e <R> \\{\\} +")
 '(grep-find-use-xargs 'exec-plus)
 '(help-enable-variable-value-editing t)
 '(help-window-keep-selected t)
 '(help-window-select t)
 '(horizontal-scroll-bar-mode nil)
 '(hscroll-margin 5)
 '(hscroll-step 1)
 '(ibuffer-default-shrink-to-minimum-size t)
 '(ibuffer-default-sorting-mode 'major-mode)
 '(ibuffer-use-other-window t)
 '(ido-ignore-directories '("\\`CVS/" "\\`\\.\\./" "\\`\\./"))
 '(ido-separator nil)
 '(ido-show-dot-for-dired t)
 '(ido-use-filename-at-point 'guess)
 '(imenu-auto-rescan t)
 '(isearch-lazy-count t)
 '(ivy-add-newline-after-prompt nil)
 '(ivy-display-style 'fancy)
 '(key-chord-mode t)
 '(large-file-warning-threshold 20000000000)
 '(line-spacing 0.1)
 '(magit-repository-directories '(("~/my_repos" . 1)))
 '(midnight-mode t)
 '(num3-group-size 4)
 '(org-M-RET-may-split-line nil)
 '(org-agenda-files '("/Users/raveenkumar/iCloud/org"))
 '(org-agenda-inhibit-startup nil)
 '(org-agenda-restore-windows-after-quit t)
 '(org-agenda-start-with-clockreport-mode nil)
 '(org-agenda-sticky t)
 '(org-blank-before-new-entry '((heading . t) (plain-list-item)))
 '(org-capture-templates
   '(("p" "Plain text capture" entry
      (file+headline "~/iCloud/org/notes.org" "* Capture")
      "" :prepend t :empty-lines-after 1)))
 '(org-cycle-hide-block-startup t)
 '(org-default-notes-file "~/iCloud/org/.notes")
 '(org-directory "~/iCloud/org")
 '(org-extend-today-until 4)
 '(org-fontify-todo-headline t)
 '(org-fontify-whole-heading-line t)
 '(org-hide-emphasis-markers t)
 '(org-hide-leading-stars t)
 '(org-id-link-to-org-use-id t)
 '(org-id-locations-file "~/iCloud/org/.org-id-locations")
 '(org-id-locations-file-relative t)
 '(org-indent-indentation-per-level 8)
 '(org-insert-heading-respect-content t)
 '(org-insert-mode-line-in-empty-file t)
 '(org-journal-dir "~/iCloud/notes")
 '(org-journal-enable-agenda-integration t)
 '(org-journal-file-type 'weekly)
 '(org-modules
   '(ol-bbdb ol-bibtex org-ctags ol-docview ol-doi ol-eww ol-gnus org-habit org-id ol-info ol-irc ol-mhe org-mouse org-protocol ol-rmail org-tempo ol-w3m ol-eshell org-annotate-file ol-bookmark org-checklist org-choose org-collector ol-elisp-symbol org-eval-light org-eval org-expiry org-learn org-notify org-panel org-screen org-screenshot org-toc org-velocity))
 '(org-pretty-entities t)
 '(org-startup-align-all-tables nil)
 '(org-startup-folded t)
 '(org-startup-indented t)
 '(org-startup-numerated nil)
 '(org-use-effective-time t)
 '(org-use-last-clock-out-time-as-effective-time nil)
 '(package-name-column-width 20)
 '(package-selected-packages '(quelpa-use-package))
 '(package-status-column-width 10)
 '(package-version-column-width 10)
 '(project-vc-extra-root-markers
   '("Makefile" "index.org" ".dir-locals.el" "README" "readme.org" "README.org" "readme"))
 '(project-vc-ignores '("TAGS" "tags"))
 '(projectile-auto-discover nil)
 '(projectile-generic-command "find -L . -type f | cut -c3- | tr '\\n' '\\0'")
 '(quit-window-hook nil)
 '(repeat-mode t)
 '(require-final-newline t)
 '(scroll-bar-mode nil)
 '(scroll-conservatively 100)
 '(set-mark-command-repeat-pop t)
 '(straight-use-package-by-default t)
 '(tags-add-tables 'ask-user)
 '(tags-revert-without-query t)
 '(three-step-help nil)
 '(todo-directory "~/iCloud/org/todo")
 '(treemacs-indent-guide-mode t)
 '(treemacs-indentation 0)
 '(treemacs-indentation-string " ┃ ")
 '(truncate-lines 1)
 '(uniquify-min-dir-content 1)
 '(vc-follow-symlinks nil)
 '(verilog-auto-newline nil)
 '(windmove-create-window nil)
 '(windmove-default-keybindings '([ignore]))
 '(windmove-mode nil)
 '(window-divider-default-places t)
 '(window-divider-mode t)
 '(window-sides-vertical t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#2e3436" :foreground "#eeeeec" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight semi-bold :height 180 :width normal :foundry "nil" :family "Fira Code"))))
 '(aw-leading-char-face ((t (:foreground "red" :height 1.0 :width extra-expanded))))
 '(cursor ((t (:background "dark cyan"))))
 '(hi-green ((t (:background "black" :foreground "light green" :slant italic :weight bold))))
 '(highlight-thing ((t (:inherit 'hi-green))))
 '(num3-face-even ((t (:foreground "orange" :background "black" :underline "yellow" :weight bold))))
 '(num3-face-odd ((t nil)))
 '(org-default ((t (:inherit default :height 250 :family "Chalkboard"))))
 '(region ((t (:extend t :background "SeaGreen1" :foreground "black")))))
