#!/usr/bin/env bash

set -e

git clone https://github.com/vim/vim.git 

cd vim
bash

./configure --prefix="$HOME/.local"  --with-features="huge" --enable-python3interp --enable-autoservername --with-x 

make -j
