#!/usr/bin/env bash

# set -euo pipefail
# IFS=$'\n\t'
# set -x

green() {
	echo -e "\e[38;5;2m"
	cat <&0
	echo -e "\e[0m"
}

red() {
	echo -e "\e[38;5;1m"
	cat <&0
	echo -e "\e[0m"
}

yellow() {
	echo -e "\e[38;5;11m"
	cat <&0
	echo -e "\e[0m"
}

blue() {
	echo -e "\e[38;5;75m"
	cat <&0
	echo -e "\e[0m"
}
