#!/usr/bin/env bash

[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"
alias find="/opt/homebrew/opt/findutils/bin/gfind"
alias xargs="/opt/homebrew/opt/findutils/bin/gxargs"
export HOMEBREW_NO_AUTO_UPDATE=1
export LESSOPEN="|/opt/homebrew/bin/lesspipe.sh %s"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH="/Library/TeX/texbin:$PATH"
export SHELL="/opt/homebrew/bin/bash"
export PATH="/opt/homebrew/opt/cyrus-sasl/sbin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$DOT/bin/macos:$PATH"
export PATH="/opt/local/bin:$PATH"

2x2() {
	[[ "${#@}" -ne 4 ]] && echo ERROR: Need 4 file names... && return 2
	vim "$4" -c "split $2 | vsplit $1 |  wincmd j | vsplit $3"
}

2x2_1() {
	[[ "${#@}" -ne 5 ]] && echo ERROR: Need 5 file names... && return 2
	vim "$4" -c "split $2 | vsplit $1 |  wincmd j | vsplit $3 | wincmd k | vsplit $5"
}
alias killsafari="osascript -e 'quit app \"safari.app\"'"
alias mail="open -a mail.app"
alias books="open \"\$(find $HOME/icloud/Documents/Shared_Documents/Books -iname '*.pdf' | fzf)\""
eval "$(/usr/libexec/path_helper)"

fortune
