# GENERATED by pi-completion-gen -- do not edit by hand; rerun generator.
# pi binary newer than this file triggers regeneration in config/bashrc.
_pi() {
  local cur c1 sf sc
  cur="${COMP_WORDS[COMP_CWORD]}"
  c1="${COMP_WORDS[1]}"
  local flags="--provider --model --api-key --system-prompt --append-system-prompt --mode --print -p --continue -c --resume -r --session --session-id --fork --session-dir --no-session --name -n --models --no-tools -nt --no-builtin-tools -nbt --tools -t --exclude-tools -xt --thinking --extension -e --no-extensions -ne --skill --no-skills -ns --prompt-template --no-prompt-templates -np --theme --use-theme --no-themes --no-context-files -nc --export --list-models --verbose --tui-mode --approve -a --no-approve -na --offline --help -h --version -v --plan"
  local cmds="install remove uninstall update list config auth mcp"
  if (( COMP_CWORD == 1 )); then
    COMPREPLY=($(compgen -W "$cmds $flags" -- "$cur"))
    return
  fi
  case "$c1" in
    install) sf="-l --local -a --approve -na --no-approve" sc="" ;;
    remove) sf="-l --local -a --approve -na --no-approve" sc="" ;;
    uninstall) sf="-l --local -a --approve -na --no-approve" sc="" ;;
    update) sf="--self --extensions --models --all --extension -a --approve -na --no-approve --force" sc="pi" ;;
    list) sf="-a --approve -na --no-approve" sc="" ;;
    config) sf="-l --local -a --approve -na --no-approve" sc="" ;;
    auth) sf="--provider --model --min-expiry --json --credentials --no-refresh" sc="print-api-key print-bearer-token check" ;;
    mcp) sf="-l --json --timeout" sc="add remove list login logout" ;;
    *) sf="$flags" sc="" ;;
  esac
  if (( COMP_CWORD == 2 )) && [[ -n "$sc" ]]; then
    COMPREPLY=($(compgen -W "$sc $sf" -- "$cur"))
    return
  fi
  COMPREPLY=($(compgen -W "$sf" -- "$cur"))
}
complete -F _pi pi
