source $VIMRUNTIME/vimrc_example.vim
set runtimepath^=~/dot/config/vim
set runtimepath^=~/dot_local/config/vim
set runtimepath+=~/dot/config/vim/after
let g:pathogen_blacklist = ['Damian-Conway-s-Vim-Setup']
if ($is_linux != "Darwin") 
    let g:pathogen_blacklist += ['vim-ai.git']
endif

execute pathogen#infect()
call pathogen#helptags()
syntax on
filetype plugin indent on

" BASICS {{{
set autoread
set nocompatible
" set hidden
set backspace=indent,eol,start
set encoding=utf-8
set noerrorbells
" set belloff=esc
set belloff=all
set novb t_vb=
" set vb t_vb=[?5h$<100>[?5l

" https://nickjanetakis.com/blog/change-your-vim-cursor-from-a-block-to-line-in-normal-and-insert-mode
" Use a line cursor within insert mode and a block cursor everywhere else.
"
" Reference chart of values:
"   Ps = 0  -> blinking block.
"   Ps = 1  -> blinking block (default).
"   Ps = 2  -> steady block.
"   Ps = 3  -> blinking underline.
"   Ps = 4  -> steady underline.
"   Ps = 5  -> blinking bar (xterm).
"   Ps = 6  -> steady bar (xterm).
" let &t_SI = "\e[5 q"
" let &t_EI = "\e[1 q"
" let &t_SR = "\e[3 q"
if &term =~ 'xterm' || &term == 'win32'
	" Use DECSCUSR escape sequences
	let &t_SI = "\e[5 q"    " blink bar
	let &t_SR = "\e[3 q"    " blink underline
	let &t_EI = "\e[1 q"    " blink block
	let &t_ti ..= "\e[1 q"  " blink block
	let &t_te ..= "\e[0 q"  " default (depends on terminal, normally blink
	" block)
endif
" }}}
" NAVIGATION {{{
set splitbelow splitright
" }}}
" GRAMMAR AND SEARCHING {{{
" set spell spelllang=en_us
" set textwidth=80
set isk+=-
set ignorecase
set smartcase
set dictionary="/usr/share/dict/words"
" }}}
" TABBING AND INDENT {{{
set tabstop=4 softtabstop=4
set shiftwidth=4
set noexpandtab
set autoindent
set smartindent
set smarttab
" set listchars=nbsp:_,tab:>-,trail:~,extends:>,precedes:<,eol:$
" set list
" }}}
" FOLDING AND WRAPPING {{{
set foldmethod=marker
set foldenable
" }}}
" {{{ NUMBERING
" set number 
" set relativenumber
set nonu nornu
" }}}
" {{{ INTERFACE
set pumheight=10
set nowrap
set nolinebreak
set hlsearch
set incsearch
set ruler
" set wildmode=list:longest,full
set wildmenu
set wildignore=#*,./,
set wildignorecase
set wildoptions=pum
" These 2 settings will force the cursor line to always be at the center of
" the screen
" set scrolloff=999
" set sidescrolloff=1
" set sidescroll=1
set scrollopt=ver,jump,hor
"  }}}
" {{{ BACKUPS AND UNDO
if ! isdirectory(expand("~/.vim/undo"))   | call mkdir(expand("~/.vim/undo"),   'p') | endif
if ! isdirectory(expand("~/.vim/backup")) | call mkdir(expand("~/.vim/backup"), 'p') | endif
set undodir=$HOME/.vim/undo
set backupdir=$HOME/.vim/backup
set makeef=/tmp/errorfile
set verbosefile=/tmp/verbosefile
set noswapfile
set backup
set writebackup
set undofile
" }}}
" {{{ NETRW
let g:netrw_liststyle = 0
let g:netrw_banner = 1
let g:netrw_hide=0
let g:netrw_keepdir=0
set browsedir="current"
"}}}
" {{{1 APPEARANCE
set previewpopup=height:10,width:60
" Remove ~ at end of file
set fillchars=eob:\ 

" {{{1 ↓ TESTING ↓
set title
set titlestring=%f
set titleold="Terminal"
set helpheight=10
function! Bookmarks()
    setlocal errorformat+=%f%.%#
    lexp  eval('g:netrw_bookmarklist')
    lopen 5
endfunction
" set complete+=t
set wildoptions=pum
set completeopt+=popup,menu,preview
" set foldclose="all"
set showfulltag
set maxcombine=6
set whichwrap+=<,>,[,]
set equalalways
" set winfixheight
" set winfixwidth
set isfname-==
set isfname-=,

packadd cfilter
set switchbuf=uselast
autocmd! BufEnter *.log setlocal readonly 
" autocmd! BufEnter *.log setlocal nowrap
" autocmd QuickFixCmdPost make set wrap
" autocmd QuickFixCmdPost make set nowinfixheight nowinfixwidth
set viminfo+=r/opt/homebrew/
set viminfo+=r~/.vim/plugged
" set exrc secure
let mapleader = " "

" set path+=**;~/ " This is awesome but find search takes too long
set tags+=./tags,../tags,~/script/tags
" set path+=*
" set path+=.*
" set path+=./;~/
set path+=~/script
set path+=~/dot/**
" autocmd! BufWritePre
" autocmd BufWritePre *.txt s/ \+$//e
" let g:ft_man_folding_enable = 1
" autocmd FileType man setlocal foldmethod=indent foldenable
let g:ft_man_no_sect_fallback = 1
set keywordprg=:Man
set hidden

if filereadable(expand('~/script/custom/custom.vim'))
    execute 'source ' . expand('~/script/custom/custom.vim')
endif
" set gdefault
"

command! Format :norm mmggVGgq`m
set showmode
set showcmd
set shortmess+=I
" set foldlevelstart=99
" func! Fix() abort
" 	let status="┆%n"
" 	if &winfixbuf
" 		let status.="┆%#Directory#FIX%*"
" 	else
" 		let status.="┆BUF"
" 	endif
" 	let status.="┆%M"
" 	let status.="┆%R"
" 	let status.="┆%f"
" 	let status.="┆%S"
" 	let status.="┆%="
" 	let status.="┆%H"
" 	let status.="┆%W"
" 	let status.="┆%Y"
" 	let status.="┆%q"
" 	let status.="┆%k"
" 	let status.="┆%p%%"
" 	" let status.="%b"
" 	" let status.="┆"
" 	let status.="┆%l,%v"
" 	let status.="┆"
" 	" let status.="%L"
" 	" let status.="┆"
" 	return status
" endfunc

set showcmd
set showcmdloc=statusline
" set statusline=\|PWD:%{getcwd()}\|FILE:%{expand('%:p')}\|
set statusline=%<%F\ %h%m%r%=%-14.(%l\/%L,%c%V%)\ %P
" set statusline=%{%Fix()%}
" set nowrap
set autochdir
" let g:deoplete#enable_at_startup = 1
			
" Repeat previous command
" nmap <leader>\ :<UP><CR>

set mouse=a
set guifont=Monaco:h24
" autocmd QuickFixCmdPost * execute 'norm G'
" BUG FIXES AND WORKAROUNDS {{{1
" Vim cant remember last cursor position in macOS
" https://github.com/vim/vim/blob/3c01c4a02897163996639f6f2604c68eab2bd18b/runtime/defaults.vim#L109-L123

if has("macunix")
	augroup vimStartup
	au!

	autocmd BufReadPost *
		\ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
	  	\ |   exe "normal! g`\""
	  	\ | endif

	augroup END
endif

set rtp+=/opt/homebrew/opt/fzf

