#!/usr/bin/env bash
 
eval "$(zoxide init bash --cmd cd)"

# cd () {
# 	__zoxide_z "$@"
# 	ls  -X --color --group-directories-first
#
# }
#
cd () {
	realpath "$1" >> /tmp/cds
	builtin cd $1 || return 2
	ls  -X --color --group-directories-first
}

cds () {
	cd "$(tac /tmp/cds | fzf +s)" || return 2
}
