#!/usr/bin/env bash
 
eval "$(zoxide init bash --cmd cd)"

# cd () {
# 	__zoxide_z "$@"
# 	ls  -X --color --group-directories-first
#
# }
#
cd () {
	builtin cd "$1" || return 2
	ls  -X --color --group-directories-first

}
