#!/usr/bin/env bash

# eval "$(zoxide init bash --cmd cd)"

# cd () {
# 	__zoxide_z "$@"
# 	ls  -X --color --group-directories-first
#
# }
#

export cds="$HOME/cds.txt"

cd() {
	if test -z "$1"; then
		builtin cd "$HOME" || return 2
	elif [[ "$1" == "-" ]]; then
		builtin cd - || return 2
	else
		builtin cd "$1" || return 2
	fi
	echo "$PWD" >> "$HOME"/cds.txt
	ls -X --color --group-directories-first
}
export -f cd

cds() {
	case "$1" in
		edit)
			$EDITOR "$cds"
			return
			;;
		*)
			echo "Wrong Option!"
			;;
	esac
	cd "$(sort "$cds" | uniq | fzf +s)" || return 2
}
export -f cds
