#!/usr/bin/env bash

link_name="$1"
# Get real path of original file
orig=$(realpath "$link_name")
# Remove link
rm "$link_name"
# Replace link with original
cp "$orig" "$link_name"
unset link_name orig
