#!/bin/bash

# set -x
# set -e

source ~/.bash_prompt

# This will auto commit, pull and push a given repository


DOTFILES=$1 # Can also sync other repos not just dotfiles. DOTFILES variable input can be any valid git repo.

[ -d $DOTFILES ] || ( echo Not a directory; exit 2 )

pushd $DOTFILES >/dev/null

if [ ! -d .git ]; then
    exit 0
fi

tmp_file="/tmp/dotfiles_sync_$$.log"

git status > "$tmp_file"

clean="0"
while read -r line; do
    if [[ "$line" =~ "nothing to commit, working tree clean" ]]; then
        clean="1"
    fi
done < "$tmp_file"


pwd
if [[ ! "$clean" == "1" ]]; then
    lazygit
    echo "Done"
fi

popd > /dev/null 

rm "$tmp_file"
