#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'
# set -x

read -p "Filename Pattern: " -re pattern
read -p "Path: " -i "$PWD" -re path

cmd="find -L $path -type f -iname '*$pattern*'"
history -s "$cmd"
readarray -t files < <(eval "$cmd")

case "${#files[@]}" in
0)
	echo "None Found..."
	code=2
	;;
1)
	$EDITOR "${files[@]}"
	code=0
	;;
*)
	# shellcheck disable=2048
	select file in "${files[@]}"; do
		$EDITOR "$file"
		break
	done
	code=0
	;;
esac

echo "Command: $cmd"
exit "$code"
