#!/usr/bin/env bash

name=$(strip_extension "$1")
output_file_name="${name}-square.jpg"

ffmpeg -i "$1" -vf "scale='min(1080,iw)':'min(1080,ih)',pad=1080:1080:(1080-iw)/2:(1080-ih)/2" "$output_file_name"
echo "$output_file_name"
