#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'
# set -x

from=$(grep -i -e "^from:" /dev/stdin)
spamstring="spam \"^From:.*$from.*\" SPAM"
echo "$spamstring"
echo -e "Added \e[31m$spamstring\e[0m to ~/script/spamrc. Restart neomutt for changes to take effect."
echo "$spamstring" >> ~/script/spamrc
$EDITOR ~/script/Spamrc
