#!/usr/bin/env bash
# Bookmark script
set -euo pipefail
IFS=$'\n\t'

file="$HOME/bookmarks.txt"

for option in "$@"; do
	case "$option" in
		list)
			urlview < <(sort "$file")
			exit 0
			;;
		edit)
			$EDITOR "$file"
			exit 0
			;;
		add)
		
			box "New bookmark"
			while read -re line ; do
				echo "$line"
			done >> "$file"
			exit 0
			;;
		*)
			echo "Error. Invalid Argument." | red
			exit 0
			;;
	esac
done

