#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'
# set -x

text="$*"
len="${#text}"
len=$((len + 4))

# printf "\t\t"
{
	jot -b - "$len" | rs -w200 -g 0
	printf "%s\n" "$text"
	jot -b - "$len" | rs -w200 -g 0
} | lolcat

exit 0
