#!/usr/bin/env bash

printf "%s\n" "----------------" | lolcat
printf "%s\n" "Capturing..." | lolcat
printf "%s\n\n\n" "----------------" | lolcat
while read -re line; do
	echo "$line"
done >>~/capture.txt

for i in $(seq 78); do
	printf "%s" "-" >>~/capture.txt
	[ "$i" -eq 78 ] && printf "\n" >>~/capture.txt
done

printf "%s\n" "----------------" | lolcat
printf "%s\n" "Captured..." | lolcat
printf "%s\n\n\n" "----------------" | lolcat
