#!/usr/bin/env bash

printf "%s\n" "Capturing..." | lolcat
{
	for i in $(seq 78); do
		printf "%s" "-"
		[ "$i" -eq 78 ] && printf "\n"
	done

	while read -re line; do
		echo "$line"
	done
} >>~/capture.txt
