#!/usr/bin/env bash

printf "%s\n" "Capturing..." | lolcat
while read -re line; do
	echo "$line"
done >>~/capture.txt

for i in $(seq 78); do
	printf "%s" "-" >>~/capture.txt
	[ "$i" -eq 78 ] && printf "\n" >>~/capture.txt
done
