#!/usr/bin/env bash

export PATH+=":~/dot/script"

find . -iname "*#*" -exec rm -i {} \;
find . -iname "*~*" -exec rm -i {} \;
[ -d ~/Downloads ] && rm -f ~/Downloads/*.dcv
find . -iname ".DS_Store" -print -delete
find . -iname "*.SVM" -print -delete
delete_empty_directories
find_broken_symlinks
