#!/usr/bin/env bash

set -eo pipefail
IFS=$'\n\t'
# set -x

[ -z "$1" ] && echo Need filename as first argument... && exit 2

file="$1"


for i in $(seq 78); do
	printf "%s" "█"
    [ "$i" -eq 78 ] && printf "\n"
done >> "$file"

while read -re line; do
	echo "$line"
done >> "$file"
