#!/usr/bin/env bash

set -eo pipefail
IFS=$'\n\t'
# set -x

pattern=${pattern:-$1}
[ -z "$pattern" ] && read -re pattern

readarray -t files < <(find . -type f -iname "*$pattern*")

[ "${#files[@]}" -eq 1 ] && $EDITOR "${files[@]}" && exit 0
# shellcheck disable=2048
select file in "${files[@]}"; do
    $EDITOR "$file"
    break
done


