#!/usr/bin/env python
"""
Python code to ask for directory and start vim FZF inside it
"""

import os
import sys
path = sys.argv[1]
os.chdir(os.path.expandvars(os.path.expanduser(path)))
os.system("vim -c FZF")
