#!/usr/bin/env bash

set -eu
set -o pipefail

count=$(find "$1" -type l ! -exec test -e {} \; -print | wc -l)
[[ $count -eq 0 ]] && exit 0


readarray -t broken_links < <(find . -type l ! -exec test -e {} \; -print)
for link in "${broken_links[@]}"; do
    echoy "Removing broken symlink..."
	sleep 0.5
    rm -v "$link"
done
