#!/usr/bin/env bash

set -e
# set -x

help () {
    less "$0"
}

if [ "$1" = "" ]; then
    path="."
else
    path="$1"
fi

find $path | xargs -I{} file {} | grep "ASCII" | grep  -v "\.git" | cut -d : -f1
