#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'
# set -x

source_if_exists ~/script/before_lg.sh

while read -u 10 -re line; do
	# gitui -d "${line/\~/$HOME}"
	lazygit -p "${line/\~/$HOME}"
	echo "${line/\~/$HOME}"
done 10<~/projects.txt
