#!/usr/bin/env bash

set -eo pipefail
IFS=$'\n\t'
# set -x

while true; do
	while read -re line; do
		lazygit -p "${line/\~/$HOME}"
	done <~/projects.txt
	[ "$1" != "loop" ] && break
	echo Looping...
	sleep 2
done
