#!/usr/bin/env bash

set -eo pipefail
IFS=$'\n\t'
# set -x

while true; do
	while read -u 10 -re line; do
		# lazygit -p "${line/\~/$HOME}"
		# echo "${line/\~/$HOME}"
		gitui -d "${line/\~/$HOME}"
	done 10<~/projects.txt
	[ "$1" != "loop" ] && break
	echo Looping...
	sleep 2
done
