#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'
# set -x

declare -a repos
repos=(
	"Quit"
	"https://github.com/junegunn/fzf/archive/refs/tags/0.48.1.tar.gz"
	"https://github.com/eradman/entr/archive/refs/tags/5.5.tar.gz"
	"https://ftp.gnu.org/gnu/bash/bash-5.1.tar.gz"
)
select repo in "${repos[@]}"; do
	[ "$repo" = "Quit" ] && exit 0
	mkdir2 ./tmp
	pushd2 ./tmp
	break
done

wget -nc "$repo"
select tarball in *.tar.gz *.tgz; do
	tar xf "$tarball"
	break
done
select dir in $(find . -type d -maxdepth 1); do
	pushd2 "$dir"
	pwd
	break
done

select config in "./configure --prefix=$HOME/.local" "./configure"; do
	eval "$config"
	break
done

make
select install in "make install" quit; do
	eval "$install"
	break
done
