#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'
# set -x

touch "$1"
tail -n 10 "$1"

while read -re line; do
	if [ "$line" = "q" ]; then
		break
	else
		echo "$line" >>"$1"
	fi
done

mpv ~/script/little-whoosh.mp3 >/dev/null 2>&1 &
exit 0
