#!/bin/bash 

delete_ds_store $HOME/my_repos
reinstall_before
sync_all_repos "$MY_REPOS"
reinstall

if [ "$1" = "x" ]; then
    echo "Shutting down in 5 seconds..."
    sudo shutdown -h now
fi

uninstall_and_cleanup_after_sync
