#!/usr/bin/env bash

{
    tput  sgr0
	for i in $(seq 256); do
		tput sgr0
		tput setab $i
        printf "Background Color $i"
		tput sgr0
        tput setaf $i
        printf "    "
        printf "Foreground Color"
        printf "    "
        tput setaf 6
		tput setab $i
        printf "CYAN Background"
        printf "\n"
	done
} | less
