#!/usr/bin/env bash 

set -e

readarray -t files < <(gfind -iname "*.org")

for file in  "${files[@]}"; do
    echo "---"
    echo "File: $file"
    new_name=$(basename -s .org "$file")
    echo "Name: $new_name"
    dir=$(dirname "$file")
    echo "Path: $dir"
    pushd "$dir"
    pandoc -s -t markdown "$new_name.org" --output="$new_name.md"
    popd
    rm -fv "$file"
done
