#!/usr/bin/env bash

set -e
# set -x

help () {
    less "$0"
}

ft="$1"
name="$2"

[[ ! -v ft ]] && echo Error! && help && exit 2
[[ ! -v name ]] && echo Error! && help && exit 2

[ ! -d ~/my_repos/dotfiles-main/stow/.vim/my_snippets/$1 ] && mkdir -p ~/my_repos/dotfiles-main/stow/.vim/my_snippets/$1

vim ~/my_repos/dotfiles-main/stow/.vim/my_snippets/$1/$2
vim ~/my_repos/dotfiles-main/stow/.vim/ftplugin/$1.vim
