#!/bin/bash

path=$(realpath $(which "$1"))

if [ -f "$path" ] && [[ "$path" =~ .*my_repos.* ]]; then
    # If path is a file inside my_repo open it in editor using realpath
    $EDITOR "$path"
    exit 0
fi

path=$(which "$1")

if [ -f "$path" ]; then
    # If path is not file inside my_repo open it in editor
    $EDITOR "$path"
    exit 0
fi

# Otherwise just print the information
which "$path"
type "$path"
whereis "$path"
exit 0
