#!/usr/bin/env bash

unset -f red; red () { tput setaf 1; }
unset -f green; green () { tput setaf 2; }
unset -f yellow; yellow () { tput setaf 3; }
unset -f blue; blue () { tput setaf 4; }
unset -f nc; nc () { tput sgr0; }

# gfind -P $1 -xtype l
count=$(find $1 -type l ! -exec test -e {} \; -print | wc -l)
[[ $count -eq 0 ]] && exit 0

blue
echo "Remove the broken links? y/n"
nc

readarray -t broken_links < <(find $1 -type l ! -exec test -e {} \; -print)
for link in ${broken_links[@]}; do
    rm -v $link
done
