#!/usr/bin/env bash 

journal=$(jrnl --list | fzf | cut -f 3 -d " ")
when="$(printf "today\nnow\n" | fzf)"

if [ "$when" = "today" ]; then
    on="-on today"
else
    on=""
fi 

jrnl "$journal" "$on" --edit

