#!/bin/bash

~/.scripts/find_broken_symlinks ~/.scripts
~/.scripts/delete_empty_directories ~/.scripts
~/.scripts/find_infinite_loop_symlinks ~/.scripts

pushd "$MY_REPOS" > /dev/null  || exit 2
for f in $(find . -iname install_everything.bash); do
    pushd "$(dirname "$f")" > /dev/null  || exit 2
    chmod +x ./install_everything.bash
    ./install_everything.bash 2>&1 | grep -v "BUG in find_stowed_path?"
    popd > /dev/null  || exit 2
done
popd > /dev/null  || exit 2


