#!/usr/bin/env bash

set -e
set -x

help () {
    less "$0"
}

while [ "$1" ]; do
    case "$1" in
        --input|-i)
            shift
            input="$1"
            ;;
        --help|-h)
            help
            ;;
        *)
            echo "ERROR! WRONG Argument!"
            help
            exit 2
            ;;
    esac
    shift
done

